@startuml

class com.frauas.exercisegenerator.documents.Author {
	{field} +createdAt : java.time.LocalDateTime
	{field} +id : String
	{field} +name : String
	{field} +updatedAt : java.time.LocalDateTime
	{method}  {static} +builder () : com.frauas.exercisegenerator.documents.Author$AuthorBuilder
	{method} #canEqual ( paramObject1 : Object ) : boolean
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class com.frauas.exercisegenerator.documents.Category {
	{field} +id : String
	{field} +name : String
	{method} #canEqual ( paramObject1 : Object ) : boolean
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class com.frauas.exercisegenerator.documents.Exercise {
	{field} +createdAt : java.time.LocalDateTime
	{field} +id : String
	{field} +updatedAt : java.time.LocalDateTime
	{method} #canEqual ( paramObject1 : Object ) : boolean
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class com.frauas.exercisegenerator.documents.ImageSolution {
	{field} +url : String
	{method} #canEqual ( paramObject1 : Object ) : boolean
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class com.frauas.exercisegenerator.documents.Sheet {
	{field} +createdAt : java.time.LocalDateTime
	{field} +id : String
	{field} +updatedAt : java.time.LocalDateTime
	{method} #canEqual ( paramObject1 : Object ) : boolean
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


abstract class com.frauas.exercisegenerator.documents.Solution {
}


class com.frauas.exercisegenerator.documents.SubExercise {
	{field} +images : java.util.List
	{field} +shortText : String
	{field} +text : String
	{field} +title : String
	{method} #canEqual ( paramObject1 : Object ) : boolean
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class com.frauas.exercisegenerator.documents.TextSolution {
	{field} +text : String
	{method} #canEqual ( paramObject1 : Object ) : boolean
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class com.frauas.exercisegenerator.documents.User {
	{field} +id : String
	{field} +password : String
	{field} +userName : String
	{method}  {static} +builder () : com.frauas.exercisegenerator.documents.User$UserBuilder
	{method} #canEqual ( paramObject1 : Object ) : boolean
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


enum com.frauas.exercisegenerator.enums.SolutionType {
	{field} +IMAGE
	{field} +TEXT
}




com.frauas.exercisegenerator.documents.Exercise "1" o-- "0..*"  com.frauas.exercisegenerator.documents.Category : categories
com.frauas.exercisegenerator.documents.Exercise "1" o-- "0..*"  com.frauas.exercisegenerator.documents.SubExercise : subExercises
com.frauas.exercisegenerator.documents.Exercise -->  com.frauas.exercisegenerator.documents.Author : author
com.frauas.exercisegenerator.documents.Exercise --|>  com.frauas.exercisegenerator.documents.SubExercise
com.frauas.exercisegenerator.documents.ImageSolution -->  com.frauas.exercisegenerator.enums.SolutionType : type
com.frauas.exercisegenerator.documents.ImageSolution --|>  com.frauas.exercisegenerator.documents.Solution
com.frauas.exercisegenerator.documents.Sheet "1" o-- "0..*"  com.frauas.exercisegenerator.documents.Category : categories
com.frauas.exercisegenerator.documents.Sheet "1" o-- "0..*"  com.frauas.exercisegenerator.documents.Exercise : exercises
com.frauas.exercisegenerator.documents.Sheet -->  com.frauas.exercisegenerator.documents.Author : author
com.frauas.exercisegenerator.documents.SubExercise "1" o-- "0..*"  com.frauas.exercisegenerator.documents.Solution : solutions
com.frauas.exercisegenerator.documents.TextSolution -->  com.frauas.exercisegenerator.enums.SolutionType : type
com.frauas.exercisegenerator.documents.TextSolution --|>  com.frauas.exercisegenerator.documents.Solution


@enduml