@startuml

class com.frauas.exercisegenerator.documents.Author {
	{field} +createdAt : java.time.LocalDateTime
	{field} +id : String
	{field} +name : String
	{field} +updatedAt : java.time.LocalDateTime
	{method}  {static} +builder () : com.frauas.exercisegenerator.documents.Author$AuthorBuilder
	{method} #canEqual ( paramObject1 : Object ) : boolean
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class com.frauas.exercisegenerator.documents.Category {
	{field} +id : String
	{field} +name : String
	{method}  {static} +builder () : com.frauas.exercisegenerator.documents.Category$CategoryBuilder
	{method} #canEqual ( paramObject1 : Object ) : boolean
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class com.frauas.exercisegenerator.documents.Course {
	{field} +id : String
	{field} +name : String
	{method}  {static} +builder () : com.frauas.exercisegenerator.documents.Course$CourseBuilder
	{method} #canEqual ( paramObject1 : Object ) : boolean
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class com.frauas.exercisegenerator.documents.Exercise {
	{field} +createdAt : java.time.LocalDateTime
	{field} +id : String
	{field} +images : java.util.List
	{field} +note : String
	{field} +shortDescription : String
	{field} +solutions : java.util.List
	{field} +texts : java.util.List
	{field} +title : String
	{field} +updatedAt : java.time.LocalDateTime
	{method} #canEqual ( paramObject1 : Object ) : boolean
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class com.frauas.exercisegenerator.documents.Sheet {
	{field} +createdAt : java.time.LocalDateTime
	{field} +id : String
	{field} +publishedAt : java.time.LocalDateTime
	{field} +title : String
	{field} +updatedAt : java.time.LocalDateTime
	{method} #canEqual ( paramObject1 : Object ) : boolean
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}


class com.frauas.exercisegenerator.documents.User {
	{field} +id : String
	{field} +password : String
	{field} +userName : String
	{method}  {static} +builder () : com.frauas.exercisegenerator.documents.User$UserBuilder
	{method} #canEqual ( paramObject1 : Object ) : boolean
	{method} +equals ( paramObject1 : Object ) : boolean
	{method} +hashCode () : int
	{method} +toString () : String
}




com.frauas.exercisegenerator.documents.Exercise "1" o-- "0..*"  com.frauas.exercisegenerator.documents.Category : categories
com.frauas.exercisegenerator.documents.Exercise "1" o-- "0..*"  com.frauas.exercisegenerator.documents.Course : courses
com.frauas.exercisegenerator.documents.Exercise -->  com.frauas.exercisegenerator.documents.Author : author
com.frauas.exercisegenerator.documents.Sheet "1" o-- "0..*"  com.frauas.exercisegenerator.documents.Category : categories
com.frauas.exercisegenerator.documents.Sheet "1" o-- "0..*"  com.frauas.exercisegenerator.documents.Exercise : exercises
com.frauas.exercisegenerator.documents.Sheet -->  com.frauas.exercisegenerator.documents.Author : author


@enduml